env:
  matrix:
    - BUILD_ENV=linuxmint-sylvia
    - BUILD_ENV=linuxmint-cindy

dist: trusty
sudo: required
services:
  - docker

script:
  - docker run -v `pwd`/output:/output linuxmintd/${BUILD_ENV} /bin/sh -c "cd /output; mint-build mint-common;"
  - docker run -v `pwd`:/source linuxmintd/${BUILD_ENV} /bin/sh -c "cd /source; mint-build;"

# deploy:
#   - provider: releases # Uploads to github
#     api_key:
#       secure:  # See Travis CI documentation
#     file: created.AppImage
#     skip_cleanup: true
#     on: # Put here conditions for deployment.
#       tags: true # This condition will only deploy on tagged commits.
