version: 2.0



jobs:

  "mint-18":
    docker:
      - image: linuxmintd/linuxmint-sylvia
    steps:
      - checkout

      - run:
          name: Build project
          command: mint-build

      - run:
          name: Prepare Packages
          command: |
            TAR=$CIRCLE_PROJECT_REPONAME_$CIRCLE_SHA1.tar
            mkdir /packages
            mv /root/*.deb /packages/
            cd /packages
            tar cvf $TAR *.deb
            gzip $TAR

      - run:
          name: Deploy to Github
          command: |
            if [ -z $CI_PULL_REQUEST ]; then
              wget https://github.com/tcnksm/ghr/releases/download/v0.5.4/ghr_v0.5.4_linux_amd64.zip
              unzip ghr_v0.5.4_linux_amd64.zip
              TAG=`git rev-parse --abbrev-ref HEAD`.$CIRCLE_JOB
              TAR=/packages/$CIRCLE_PROJECT_REPONAME_$CIRCLE_SHA1.tar.gz
              ./ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -replace $TAG $TAR
              ./ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -recreate -b "Latest unstable packages" $TAG $TAR
            fi

workflows:
  version: 2
  build:
    jobs:
      - "mint-18"
