version: 2.0



jobs:

  "mint-18":
    docker:
      - image: linuxmintd/linuxmint-sylvia
    steps:
      - checkout

      - run:
          name: Build project
          command: mint-build

      - run:
          name: Prepare Packages
          command: |
            mkdir /packages;
            mv /root/*.deb /packages/;

      - run:
          name: Deploy to Github
          commands: |
            wget https://github.com/tcnksm/ghr/releases/download/v0.5.4/ghr_v0.5.4_linux_amd64.zip
            unzip ghr_v0.5.4_linux_amd64.zip
              ./ghr -draft -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -b "blah" -replace $CIRCLE_TAG /packages

workflows:
  version: 2
  build:
    jobs:
      - "mint-18"
