version: 2.0

jobs:

  "mint-17":
    docker:
      - image: linuxmintd/linuxmint-rosa
    steps:
      - checkout
      - run:
          name: Build project
          command: dpkg-buildpackage

  "mint-18":
    docker:
      - image: linuxmintd/linuxmint-sylvia
    steps:
      - checkout
      - run:
          name: Build project
          command: dpkg-buildpackage

workflows:
  version: 2
  build:
    jobs:
      - "mint-17"
      - "mint-18"
