version: 2.0



jobs:

  "mint-18":

    docker:
      - image: linuxmintd/linuxmint-sylvia

    build:
      - checkout

      - run:
        name: Build project
        command: mint-build

      - run:
        name: Prepare Packages
        command: |
          mkdir /packages;
          mv /root/*.deb /packages/;

    dependencies:
      pre:
        - go get github.com/tcnksm/ghr

    deploy:
      requires:
        build

      release:
        branch: master
        commands:
          - ghr --username tcnksm-sample --token $GITHUB_TOKEN --replace --prerelease --debug pre-release /packages/

workflows:
  version: 2
  build:
    jobs:
      - "mint-18"
